# Generated by Django 5.2.8 on 2025-11-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='transfer_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
