# Generated by Django 5.2.8 on 2025-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_created_at_alter_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='printer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='workstation_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
