# Generated by Django 5.2.8 on 2025-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_attendance_tenant_attendancesummary_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Encoded face data for recognition (JSON array)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(blank=True, help_text='Reference face image for recognition', null=True, upload_to='employees/faces/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered',
            field=models.BooleanField(default=False, help_text='Whether face recognition is registered for this employee'),
        ),
    ]
