# Generated by Django 5.2.8 on 2025-11-24 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Judul')),
                ('original_image', models.ImageField(upload_to='tools/images/original/', verbose_name='Gambar Asli')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='tools/images/compressed/', verbose_name='Gambar Terkompresi')),
                ('quality', models.IntegerField(default=80, verbose_name='Kualitas (%)')),
                ('max_width', models.IntegerField(blank=True, null=True, verbose_name='Lebar Maks')),
                ('max_height', models.IntegerField(blank=True, null=True, verbose_name='Tinggi Maks')),
                ('output_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], default='jpeg', max_length=10, verbose_name='Format Output')),
                ('original_size', models.PositiveIntegerField(default=0, verbose_name='Ukuran Asli (bytes)')),
                ('compressed_size', models.PositiveIntegerField(default=0, verbose_name='Ukuran Terkompresi (bytes)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compressed Image',
                'verbose_name_plural': 'Compressed Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('operation_type', models.CharField(choices=[('merge', 'Gabung'), ('split', 'Pisah'), ('compress', 'Kompres')], max_length=20, verbose_name='Jenis Operasi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Judul')),
                ('page_ranges', models.CharField(blank=True, help_text='Untuk split: 1-3,5,7-10', max_length=500, verbose_name='Range Halaman')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='tools/pdf/results/', verbose_name='File Hasil')),
                ('input_page_count', models.PositiveIntegerField(default=0)),
                ('output_page_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Operation',
                'verbose_name_plural': 'PDF Operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFInputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('file', models.FileField(upload_to='tools/pdf/inputs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='tools.pdfoperation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('content_type', models.CharField(choices=[('url', 'URL'), ('text', 'Teks'), ('vcard', 'vCard'), ('wifi', 'WiFi'), ('email', 'Email'), ('phone', 'Telepon'), ('sms', 'SMS')], default='url', max_length=20, verbose_name='Jenis Konten')),
                ('content', models.TextField(verbose_name='Konten')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Judul')),
                ('size', models.IntegerField(default=300, verbose_name='Ukuran (px)')),
                ('error_correction', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('Q', 'Quartile'), ('H', 'High')], default='M', max_length=1, verbose_name='Error Correction')),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tools/qrcodes/', verbose_name='QR Code Image')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('original_url', models.URLField(max_length=2048, verbose_name='URL Asli')),
                ('short_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Kode Pendek')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Judul')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Klik')),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Kedaluwarsa')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Password')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='URLClickLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=2048)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='tools.shortenedurl')),
            ],
            options={
                'verbose_name': 'URL Click Log',
                'verbose_name_plural': 'URL Click Logs',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['short_code'], name='tools_short_short_c_8cc8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['created_by', '-created_at'], name='tools_short_created_7d9b17_idx'),
        ),
    ]
