# Generated by Django 5.2.8 on 2025-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlclicklog',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='urlclicklog',
            index=models.Index(fields=['shortened_url', '-clicked_at'], name='tools_urlcl_shorten_a0cc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclicklog',
            index=models.Index(fields=['device_type'], name='tools_urlcl_device__bdcfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclicklog',
            index=models.Index(fields=['browser'], name='tools_urlcl_browser_7dac83_idx'),
        ),
        migrations.AddIndex(
            model_name='urlclicklog',
            index=models.Index(fields=['country_code'], name='tools_urlcl_country_c32cce_idx'),
        ),
    ]
