# Generated by Django 5.2.8 on 2025-11-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('tools', '0002_urlclicklog_browser_urlclicklog_browser_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pdfinputfile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pdfoperation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='urlclicklog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
