# Generated by Django 5.2.8 on 2025-11-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
