# Generated by Django 5.2.8 on 2025-11-24 04:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('request_number', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True, help_text='Tujuan/keperluan pengeluaran')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('expense_date', models.DateField(help_text='Tanggal pengeluaran')),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('submitted', 'Diajukan'), ('pending_approval', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('processing', 'Diproses'), ('paid', 'Dibayar'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('petty_cash', 'Kas Kecil')], default='bank_transfer', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('finance_notes', models.TextField(blank=True, help_text='Catatan dari finance')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_expenses', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Request',
                'verbose_name_plural': 'Expense Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('travel', 'Perjalanan Dinas'), ('accommodation', 'Akomodasi'), ('meals', 'Makan & Minum'), ('transport', 'Transportasi'), ('supplies', 'Perlengkapan'), ('entertainment', 'Jamuan Tamu'), ('training', 'Pelatihan'), ('communication', 'Komunikasi'), ('utilities', 'Utilitas'), ('medical', 'Kesehatan'), ('other', 'Lainnya')], default='other', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses/receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('expense_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.expenserequest')),
            ],
            options={
                'verbose_name': 'Expense Item',
                'verbose_name_plural': 'Expense Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('advance_number', models.CharField(max_length=30, unique=True)),
                ('purpose', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('disbursed', 'Dicairkan'), ('settled', 'Diselesaikan'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_advances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('expense_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='finance.expenserequest')),
            ],
            options={
                'verbose_name': 'Expense Advance',
                'verbose_name_plural': 'Expense Advances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['request_number'], name='finance_exp_request_2a4d58_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['requester'], name='finance_exp_request_c67d73_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['status'], name='finance_exp_status_0ce0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['request_date'], name='finance_exp_request_3c091a_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_105476_idx'),
        ),
    ]
