# Generated by Django 5.2.8 on 2025-11-29 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('prefix', models.CharField(blank=True, help_text='e.g., Dr., Prof., Hon.', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g., Ph.D., MBA', max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('phone_mobile', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('expertise_areas', models.JSONField(blank=True, default=list, help_text='List of expertise areas')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Languages spoken')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='internal', help_text='Controls who can view this contact', max_length=20)),
                ('contact_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member responsible for this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('email', 'Email'), ('lunch', 'Lunch/Dinner'), ('event', 'Event'), ('conference', 'Conference'), ('collaboration', 'Collaboration'), ('other', 'Other')], default='meeting', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True, help_text='Meeting outcome/notes')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('organized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_activities', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='contact_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact Activities',
                'db_table': 'crm_contact_activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to author and admins')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.contact')),
            ],
            options={
                'db_table': 'crm_contact_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('government', 'Government Agency'), ('corporate', 'Corporate'), ('ngo', 'NGO/Non-Profit'), ('education', 'Educational Institution'), ('media', 'Media'), ('partner', 'Partner Organization'), ('vendor', 'Vendor/Supplier'), ('donor', 'Donor'), ('other', 'Other')], default='other', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='internal', max_length=20)),
                ('logo', models.URLField(blank=True, help_text='URL to organization logo')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='crm.organization')),
            ],
            options={
                'db_table': 'crm_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title/position', max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the contact's primary position?")),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently active', null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('office_phone', models.CharField(blank=True, max_length=50)),
                ('office_email', models.EmailField(blank=True, max_length=254)),
                ('office_address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crm.organization')),
            ],
            options={
                'db_table': 'crm_job_positions',
                'ordering': ['-is_current', '-is_primary', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_d1ddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email_primary'], name='crm_contact_email_p_aa3291_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['access_level'], name='crm_contact_access__deb740_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='crm_contact_contact_19fc20_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_to'], name='crm_contact_assigne_b421df_idx'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['contact', '-activity_date'], name='crm_contact_contact_4842db_idx'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['activity_type'], name='crm_contact_activit_6f96fe_idx'),
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['requires_followup'], name='crm_contact_require_345143_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnote',
            index=models.Index(fields=['contact', '-created_at'], name='crm_contact_contact_c25a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnote',
            index=models.Index(fields=['author'], name='crm_contact_author__add169_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='crm_organiz_name_743c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='crm_organiz_organiz_7e1633_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['access_level'], name='crm_organiz_access__8b6dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['contact', 'organization'], name='crm_job_pos_contact_e65f25_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['is_current'], name='crm_job_pos_is_curr_5ea6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['is_primary'], name='crm_job_pos_is_prim_548d61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobposition',
            unique_together={('contact', 'organization', 'title', 'start_date')},
        ),
    ]
