# Generated by Django 5.2.8 on 2025-11-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True, help_text='URL or base64 data URI for organization logo'),
        ),
    ]
