# Generated by Django 5.2.8 on 2025-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo_url',
            field=models.TextField(blank=True, help_text='URL or base64 data URI for contact photo'),
        ),
    ]
