import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

// Configure fonts with stable options
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "500", "600", "700"],
  variable: '--font-inter',
});

const playfair = Playfair_Display({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "500", "600", "700"],
  variable: '--font-playfair',
});

// Add any necessary global metadata here
export const metadata: Metadata = {
  title: "Nalar", // Example Title
  description: "Generated by create next app", // Example Description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
      <body className="font-sans antialiased min-h-screen">{children}</body>
    </html>
  );
} 