import type { Metadata } from "next";
import { Inter, PT_Sans } from "next/font/google";
import "./globals.css";

// Configure fonts with stable options
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "500", "600", "700"],
  variable: '--font-inter',
});

const ptSans = PT_Sans({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "700"],
  variable: '--font-pt-sans',
});

// Add any necessary global metadata here
export const metadata: Metadata = {
  title: "Nalar", // Example Title
  description: "Generated by create next app", // Example Description
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${ptSans.variable}`}>
      <body className="font-sans antialiased min-h-screen" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
} 