# Generated by Django 5.2.8 on 2025-11-23 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('public', 'Publik'), ('internal', 'Internal'), ('confidential', 'Rahasia'), ('restricted', 'Sangat Rahasia')], default='internal', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('policy', 'Kebijakan'), ('procedure', 'Prosedur'), ('report', 'Laporan'), ('contract', 'Kontrak'), ('memo', 'Memo'), ('letter', 'Surat'), ('form', 'Formulir'), ('manual', 'Manual'), ('other', 'Lainnya')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('pending_review', 'Menunggu Review'), ('approved', 'Disetujui'), ('published', 'Dipublikasi'), ('archived', 'Diarsipkan'), ('expired', 'Kadaluarsa')], default='draft', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_nonce', models.CharField(blank=True, help_text='Base64-encoded nonce for AES-GCM decryption', max_length=32)),
                ('access_level', models.CharField(choices=[('public', 'Publik'), ('internal', 'Internal'), ('confidential', 'Rahasia'), ('restricted', 'Sangat Rahasia')], default='internal', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action', models.CharField(choices=[('view', 'Dilihat'), ('download', 'Diunduh'), ('edit', 'Diedit'), ('delete', 'Dihapus'), ('share', 'Dibagikan'), ('access_denied', 'Akses Ditolak')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='documents_d_documen_003c8f_idx'), models.Index(fields=['user', 'created_at'], name='documents_d_user_id_e6c81f_idx'), models.Index(fields=['action'], name='documents_d_action_2c9060_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('legal', 'Legal'), ('it', 'IT'), ('research', 'Research'), ('operations', 'Operations'), ('executive', 'Executive'), ('staff', 'Staff')], max_length=20)),
                ('can_read', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Access Permission',
                'verbose_name_plural': 'Document Access Permissions',
                'indexes': [models.Index(fields=['document', 'role'], name='documents_d_documen_210831_idx')],
                'unique_together': {('document', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DocumentUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='documents.document')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document User Access',
                'verbose_name_plural': 'Document User Access',
                'indexes': [models.Index(fields=['document', 'user'], name='documents_d_documen_9d02a8_idx'), models.Index(fields=['expires_at'], name='documents_d_expires_da0eab_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='documents_f_parent__c80268_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner'], name='documents_f_owner_i_e97ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['access_level'], name='documents_f_access__6654e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_2c6923_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level'], name='documents_d_access__2eb685_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='documents_d_folder__b9ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='documents_d_owner_i_fa3cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['effective_date'], name='documents_d_effecti_8d4819_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
    ]
